// tslint:disable
/**
 * 🦊 API
 * The 🦊 API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    DateResponseDto,
} from '../models';

/**
 * no description
 */
export class AppApi extends BaseAPI {

    /**
     */
    appControllerGetCurrentDate(): Observable<DateResponseDto>
    appControllerGetCurrentDate(opts?: OperationOpts): Observable<AjaxResponse<DateResponseDto>>
    appControllerGetCurrentDate(opts?: OperationOpts): Observable<DateResponseDto | AjaxResponse<DateResponseDto>> {
        return this.request<DateResponseDto>({
            url: '/date',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    appControllerPing(): Observable<void>
    appControllerPing(opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    appControllerPing(opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        return this.request<void>({
            url: '/ping',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
